version: '3.7'
services:
  apache:
    build: 
      context: ./apache/
      dockerfile: Dockerfile
    env_file:
     - ./config.env
    ports:
      - "80:80"
  loganfordnet:
    build:
      context: ./loganfordnet/
      dockerfile: Dockerfile
    env_file:
      - ./config.env
    volumes:
      - ${LFN_ROOT}:/home/loganfordnet
    depends_on:
      - mysql
    command: ["./startup.sh"]
  mysql:
    image: mysql
    env_file:
     - ./config.env
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ${V_ROOT}/mysql:/var/lib/mysql
  jellyfin:
    image: linuxserver/jellyfin
    env_file:
      - ./config.env
    environment:
      - UMASK_SET=022 #optional
    volumes:
      - ${V_ROOT}/jellyfin/config:/config
      - ${V_ROOT}/jellyfin/data/tvshows:/data/tvshows
      - ${V_ROOT}/jellyfin/data/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920
    restart: unless-stopped
  ombi:
    restart: always
    image: linuxserver/ombi
    volumes:
      - ${V_ROOT}/ombi/config:/config
    env_file:
      - ./config.env
  radarr:
    image: "linuxserver/radarr"
    volumes:
      - ${V_ROOT}/radarr/config:/config
      - ${V_ROOT}/jellyfin/movies:/movies
      - ${V_ROOT}/transmission/data/completed:/data/completed
    restart: always
    env_file:
      - ./config.env
  sonarr:
    image: "linuxserver/sonarr"
    volumes:
      - ${V_ROOT}/sonarr/config:/config
      - ${V_ROOT}/sonarr/downloads:/downloads
      - ${V_ROOT}/sonarr/tv:/tv
    restart: always
    env_file:
      - ./config.env
  transmission-vpn:
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
    - "9091:9091"
    - "51413:51413"
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - ${V_ROOT}/transmission/data:/data
      - ${V_ROOT}/transmission/data/watch:/data/watch
      - ${V_ROOT}/transmission/data/completed:/data/completed
      - ${V_ROOT}/transmission/data/incomplete:/data/incomplete
    env_file:
      - ./config.env
    environment:
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
  jackett:
    image: "linuxserver/jackett"
    volumes:
      - ${V_ROOT}/jackett/config:/config
      - ${V_ROOT}/jackett/downloads:/downloads
    restart: always
    env_file:
      - ./config.env
  teamspeak:
    image: mbentley/teamspeak:alpine 
    restart: always
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    env_file:
      - ./config.env
    volumes:
      - ${V_ROOT}/teamspeak:/data