version: '3.7'
services:
  apache:
    build: 
      context: ./apache/
      dockerfile: Dockerfile
    env_file:
     - ./config.env
    ports:
      - "80:80"
    depends_on:
      - mysql
    command: ["./apache-start.sh"]
  mysql:
    image: mysql
    env_file:
     - ./config.env
    command: --default-authentication-plugin=mysql_native_password
    restart: always
