"""empty message

Revision ID: 89a1a8b84c14
Revises: 
Create Date: 2019-06-14 22:29:20.806464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89a1a8b84c14'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page',
    sa.Column('id', mysql.INTEGER(), nullable=False),
    sa.Column('title', mysql.VARCHAR(charset='utf8mb4', length=100), nullable=False),
    sa.Column('url', mysql.VARCHAR(charset='utf8mb4', length=256), nullable=False),
    sa.Column('display_in_sidebar', mysql.INTEGER(), nullable=False),
    sa.Column('created_by_id', mysql.INTEGER(), nullable=False),
    sa.Column('created_date', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_page_created_by_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_page')),
    sa.UniqueConstraint('url', name=op.f('uq_page_url'))
    )
    op.create_index(op.f('ix_page_id'), 'page', ['id'], unique=False)
    op.create_table('page_history',
    sa.Column('id', mysql.INTEGER(), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('version', mysql.INTEGER(), nullable=False),
    sa.Column('last_modified_by_id', mysql.INTEGER(), nullable=False),
    sa.Column('last_modified_date', mysql.TIMESTAMP(), nullable=True),
    sa.Column('page_id', mysql.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['last_modified_by_id'], ['user.id'], name=op.f('fk_page_history_last_modified_by_id_user')),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], name=op.f('fk_page_history_page_id_page')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_page_history'))
    )
    op.create_index(op.f('ix_page_history_id'), 'page_history', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_history_id'), table_name='page_history')
    op.drop_table('page_history')
    op.drop_index(op.f('ix_page_id'), table_name='page')
    op.drop_table('page')
    # ### end Alembic commands ###
